#!/bin/sh
set -eu

STATE_DIR="${STATE_DIR:-state}"

if [ -d "$STATE_DIR/hypercorn/secrets" ]
then
  find "$STATE_DIR/hypercorn/secrets" -type f -exec chmod 400 {} +
fi

if [ -d "$STATE_DIR/secrets" ]
then
  find "$STATE_DIR/secrets" -type f ! -name "apptoken.txt" -exec chmod 400 {} +
  find "$STATE_DIR/secrets" -type f -name "apptoken.txt" -exec chmod 600 {} +
fi
